### PR TITLE
Websocket updates

### LINKED ISSUE #37: muster-server caches query
**Describe the bug**

This is a follow-up of #27 - turns out the issue is at the server-side, and in the `muster-server` implementation specifically. For whatever reason, requests are being cached and the new graph state is not returned after the first `set()` operation. What's more, the obsolete graph state is returned even after a full reload of the page, or from two independent browsers. 

**To Reproduce**

Muster is setup within Express like so:

```javascript

const musterApp = muster({
  accounts: {
     [match(types.string, 'id')]: fromPromise({
         get: fetchItem,
         set: updateItem // update item and invalidate ref('accounts')
     }),
     [match(types.object, 'filter')]: fromPromise({
         get: findAll,
         set: updateAll // update items and invalidate ref('accounts')
     })
  }
});

musterApp.resolve(query(ref('accounts', {}), entries({ // findAll
    id: true, firstName: true, lastName: true, fullName: true
}))).subscribe(function(result) {
    console.log(JSON.stringify(result, null, 4));
});

app.post('/muster', cors(), bodyParser.json(), musterExpress(musterApp));
```

**Expected behavior**

Client-side, the following code should update the item, invalidate the remote, and automatically re-trigger the subscriber function. However, this function is only called twice - once in initialization, and once after the first successful update.

After that, on a page reload, only the initialization triggers it, and even though it's updated again soon thereafter, it's never triggered again. On reload, the value stays at the first timestamp value set. Even though *the data on the server is updated correctly* each time, no matter what you do, the initial timestamp is returned to the client graph (as mentioned, page reload, different browsers, etc.). This is already the case inside the Express middleware - so it's not the browser caching it (it wouldn't cache POST anyway).

```javascript
const clientApp = muster({
    api: remote('http://localhost:8000/muster', {
        requestTimeout: 2000
    })
});

let q = query(ref('api', 'accounts', 'wilma'), {
    id: true,
    firstName: true,
    lastName: true,
    fullName: true
});

clientApp.resolve(q).subscribe(function(result) {
    console.log(JSON.stringify(result, null, 4));
});

setTimeout(function() {
    const r = ref('api', 'accounts', 'wilma');
    clientApp.resolve(set(r, {
        firstName: new Date().getTime()
    })).then(function(result) {
        return clientApp.resolve(invalidate(ref('api'))).then(function() {
            console.log('Invalidated');
        });
    });
}, 1200);
```
**Desktop (please complete the following information):**
 - OS: [e.g. MacOS]
 - Browser [chrome, safari]

**Additional context**

It appears to be related to the ` [match(types.string, 'id')]` construct, together with the `fromPromise` and `set` operation. For example, the same thing using a `set` operation on `[match(types.object, 'filter')]` does work fine (updating all matching items). Same for `[match(types.array, 'ids')]` if it were specified. It's the scalar types that are never released (and remain retained/cached).

### PR DESCRIPTION
**Pull request by dws-dave**
Fix #37

### CODE REVIEW

File: packages/muster-remote/src/socket.ts [hunk 1]
```diff
@@ -166,17 +166,19 @@ export default class ReconnectingWebSocket {
   removeEventListener(method: 'error', cb?: (error: Error) => void): void;
   removeEventListener(method: 'open', cb?: () => void): void;
   removeEventListener(method: string, listener: () => void): void {
-    const handlerIndex = this.handlers[method].indexOf(listener, 1);
```
Comment (dws-dave) [inline packages/muster-remote/src/socket.ts]: nobody look at this bit 😳

Comment (dws-sam) [reply packages/muster-remote/src/socket.ts]: *looks*

Comment (dws-tomasz) [reply packages/muster-remote/src/socket.ts]: this-is-fine
